### ISSUE TITLE
Install doesn't note requirement of pandas

### ISSUE THREAD

**Issue by WillAdams** [Heron-Repositories/Heron#5]
When I tried to install and run it, after following all the instructions it complained that pandas wasn't installed --- should that be added?

**Comment by georgedimitriadis** [comment]
Hey,

Thanks for noticing this. 

I have concentrated on getting the manual sorted and have ignored the readme here. 

On the manual's installation page https://heron-42ad.readthedocs.io/en/latest/source/documentation/installation.html#installation there is a detailed description of the correct way to install.

I will update the readme soon
